### PR TITLE
Walk small feature

### PR DESCRIPTION
**Pull request by oarsc**
I just created a few changes similar of what I had on my client, but I don't know if you will like them or this will work Ok in all versions. It has nothing to do with #112 

The first change is to schedule the next step when double tapping, even if it's in the same direction. Tibia actually works that way.
Pressing Up-Arrow twice does 2 steps (doesn't work pressing it thrice). I had to pass a new boolean of keyDown to detect this case.

The other change is to prevent the character to stop abruptly after you stop pressing the key just before finishing a step.
This might be a more controversial modification, because you lose a bit of control over the movement, but I feel like it's more natural this way. (Tibia also does something similar to this)
The implementation of this second behavior could be better, because now it's creating an scheduledEvent for every step, not only when the key is up, but this can be improved in the future.

### CODE REVIEW

**Comment by mehah** [comment]
you can put as something optional in the menu and whoever wants to make this system mandatory, just force a true and take it in the options screen.

**Comment by oarsc** [comment]
Added "Enable precise control" option.
It is disabled by default, and turning it on, you can restore old behavior.

It only applies the "delayed stop" that I mentioned. I added an user friendly explanation as a tooltip in the option.
The "double tap-double step" thing is always enabled always, as I don't think it will cause any problem

**Comment by mehah** [comment]
you could bundle this code into c++ and use a flag to enable and disable, something like this:

```cpp
if(!m_localPlayer->canWalk(direction)) {
	const float ticks = std::max<float>(m_localPlayer->getStepTicksLeft(), 1);
	if(m_lastWalkDir != direction && (!m_scheduleLastWalk || ticks < std::min<int>(m_localPlayer->getStepDuration()/2, 250))) {
		// must add a new walk event
		if(m_walkEvent) {
			m_walkEvent->cancel();
			m_walkEvent = nullptr;
		}

		m_walkEvent = g_dispatcher.scheduleEvent([=] { walk(direction); }, ticks);
		m_nextScheduledDir = direction;
	}
	return false;
} else if(m_scheduleLastWalk) {
	m_nextScheduledDir = Otc::InvalidDirection;
	// if it's going to walk, but there is another scheduled event, cancel it
	if(m_walkEvent && !m_walkEvent->isExecuted()) {
		m_walkEvent->cancel();
		m_walkEvent = nullptr;
	}
}
```

```cpp
void setScheduleLastWalk(const bool v) { m_scheduleLastWalk = v;}
bool isEnabledSchedulerLastWalk() { return m_scheduleLastWalk;}

bool m_scheduleLastWalk{true};
```

in lua
```lua
g_game.setScheduleLastWalk(true);
```

**Comment by mehah** [comment]
honestly, i haven't tested this modification, if you think it doesn't affect anything, with the current code, for me you don't need to set a flag, i'm just worried if any user complains about this modification, that's why i suggested an enable/disable option .

**Comment by oarsc** [comment]
In the last commit, I separated the logic to prevent creating an scheduled task for every step if not needed.
If there isn't any problem with that, I can do what you said.

About the option thing, I will leave it there for a while and see if somebody reports something about this change and remove it later.
Or maybe keep it there and let the user play the way he's used to.

**Comment by oarsc** [comment]
Ok, I added your c++ flag, because there was a turn bug, and it was easier to fix this way.
We can always improve it ;)
I'm merging it

**Pull request merged**
