### PR TITLE
Fix custom spells support in actionbar

### PR DESCRIPTION
**Pull request by Znote**
The actionbar module had like 90% support for adding custom spells, there was just a few things that was hardcoded for the default list. And since there wasnt an easy way to demo how custom spells works, it was a bit tricky to get started with. 

This PR fixes that, if you add custom spells, they will appear in the `Assign Spell` window in-game.
image

To demo, just follow the tutorial, but only uncomment. Demo spells will appear in the list.
## Tutorial: (psst... Please enable mehah/otclient repo Wiki)
Edit `modules/gamelib/spells.lua`
- Uncomment `Custom` section of the `SpelllistSettings` table.
  - In `spellOrder`, add a unique list of your spell names (not needed if you just wanna demo)
- Uncomment `Custom` section of the `SpellInfo` table. 
  - Add and edit the spell information here. (not needed if you just wanna demo)

Edit `data/images/game/spells/custom.png` (not needed if you just wanna demo)
- Each spell square should match configured `iconSize` in `SpelllistSettings`.

Restart client and see your spells in actionbar. 👍

### CODE REVIEW

**Comment by poxis** [comment]
Graphics are a bit average ;d 
Or maybe add bigger font and make it like abbreviation of first letters, but generate it on the image, because it will be a bit cumbersome.

**Comment by Znote** [comment]
Haha, yeah those graphics are just shitty placeholders, but easy to edit (if ur not me). I'm no artist. xD
But should anyone want to make thematically good and correct spellsquares for my 8 custom spells, I'll throw a donation your way. 👍 I happen to be in need of some artist work on AcidsOT.

But since this is a small sample file just to showcase how adding custom spells work on the client, and to easily demo it, I don't think it should be a PR showstopper.

**Comment by oarsc** [comment]
Actually, IMO I wouldn't add that sample png. People can already take as a sample the defaultspells.png

**Comment by Znote** [comment]
I wouldn't recommend using the same image file for both default and custom spells. Duplicating default spells images and rename it custom wouldn't be good either, as its not very obvious if it worked properly when enabling custom spells. 

Right now, all you need to do to demo spells is to uncomment 2 sections in spells.lua. 
If we remove the image, they have to uncomment and add an image, preferably one that doesn't contain default icons. Suddenly the simple idea of testing how things work becomes a complicated ordeal. 

Its a small image to save big time.

**Comment by oarsc** [comment]
I don't really know about how easy do we have to leave things for those who want to use them 😂 .

I can't give permissions to wiki, but I can create pages. Don't know how wiki's permissions work @mehah

**Comment by oarsc** [comment]
Created https://github.com/mehah/otclient/wiki/Tutorial:-Create-custom-spells

**Comment by mehah** [comment]
> I don't really know about how easy do we have to leave things for those who want to use them 😂 .
> 
> I can't give permissions to wiki, but I can create pages. Don't know how wiki's permissions work @mehah

now @Znote is a contributor, it should be able to edit the wiki.

**Pull request merged**
