### PR TITLE
Bye Boost Lib :raised_hands:	

### PR DESCRIPTION
**Pull request by mehah**
well, the name says, many of the things we were using from the boost lib, already exist in c++20, which does not exist, equivalent methods were created or replaced by other libs, with that, we reduced the size of the executable and it will take less time to download the libs in vcpkg.

Note: 
[32bits]
vcpkg install asio:x86-windows

[64bits]
vcpkg install asio:x64-windows

[static 32bits]
vcpkg install --triplet x86-windows-static asio

### CODE REVIEW

**Comment by nekiro** [comment]
Kinda sad that stduuid is not available from vcpkg :(

**Comment by nekiro** [comment]
I think this PR breaks compilation on ubuntu 20.04, `#include <span>` which is used by uuid is not available under ubuntu 20.04
source: https://github.com/mgbowen/windows-fido-bridge/issues/15

**Comment by mehah** [comment]
> Kinda sad that stduuid is not available from vcpkg :(

I opened an issue: https://github.com/mariusbancila/stduuid/issues/63

> I think this PR breaks compilation on ubuntu 20.04, `#include <span>` which is used by uuid is not available under ubuntu 20.04 source: [mgbowen/windows-fido-bridge#15](https://github.com/mgbowen/windows-fido-bridge/issues/15)

there is a solution for this: https://github.com/mariusbancila/stduuid/issues/60#issuecomment-1062204834
but our project is c++20, let's wait for @scopz to test it, since his is ubuntu 20

**Comment by nekiro** [comment]
> > Kinda sad that stduuid is not available from vcpkg :(
> 
> I opened an issue: [mariusbancila/stduuid#63](https://github.com/mariusbancila/stduuid/issues/63)
> 
> > I think this PR breaks compilation on ubuntu 20.04, `#include <span>` which is used by uuid is not available under ubuntu 20.04 source: [mgbowen/windows-fido-bridge#15](https://github.com/mgbowen/windows-fido-bridge/issues/15)
> 
> there is a solution for this: [mariusbancila/stduuid#60 (comment)](https://github.com/mariusbancila/stduuid/issues/60#issuecomment-1062204834) but our project is c++20, let's wait for @scopz to test it, since his is ubuntu 20

Well, we are not using stduuids cmake, cause you included the raw code into otclient, so that won't work, uuid.h includes <span> from std library, and that's not present on ubuntu 20.04 (I tested compiling it there), so we probably need gsl to use instead (that's configured in cmake), that would mean we have to include gsl into otclient source too.

EDIT:
I got it working by updating g++ to version 10 which includes span, but do we want that hassle just to add this uuid library?

source:
https://askubuntu.com/questions/1263704/how-do-i-install-gcc-10-2-with-sudo-apt-get-install-gcc-x-g-x
https://tuxamito.com/wiki/index.php/Installing_newer_GCC_versions_in_Ubuntu

how to update g++:

```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install -y g++-11
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 6
sudo update-alternatives --config gcc
gcc --v
```

compilation:
image

**Comment by mehah** [comment]
> EDIT: I got it working by updating g++ to version 10 which includes span, but do we want that hassle just to add this uuid library?

well i don't see the problem, we put a solve saying we need gcc 10+.

when stduuid goes to vcpkg, I remove it from the code, because I don't like it to be like that.

so can we proceed with the merger?  :grinning:

**Comment by oarsc** [comment]
After
`sudo apt-get install -y libasio-dev`

it's building fine to me 👍🏼

**Review by oarsc — DISMISSED** [review]

**Comment by oarsc** [comment]
I assume, after these changes, there won't be any need to install `libboost-all-dev`, right?
We have to update wikis

**Comment by mehah** [comment]
> 

maybe we have to change cmake too.
https://github.com/mehah/otclient/blob/5a1403a33a6f427468a907ebbd0ecfe6fd5451ee/src/framework/CMakeLists.txt#L192

**Comment by nekiro** [comment]
If boost is completely not used, we can remove it

**Comment by oarsc** [comment]
What about 
https://github.com/mehah/otclient/blob/2101afa0c192c43ee07b3b222b989142feab5506/src/framework/sql/database.h#L29

**Comment by nekiro** [comment]
> What about
> 
> https://github.com/mehah/otclient/blob/2101afa0c192c43ee07b3b222b989142feab5506/src/framework/sql/database.h#L29

I think we could just get rid of this, its useless feature to have sql in client and I cant even see potential use for it XD
Visual Studio doesn't even compile this file, because its not added to it.

**Comment by mehah** [comment]
> I think we could just get rid of this, its useless feature to have sql in client and I cant even see potential use for it XD Visual Studio doesn't even compile this file, because its not added to it.

I agree, I'll remove it in the next cleanup-related PR I'm doing, besides, the mysql library only has it for x64.
https://github.com/microsoft/vcpkg/issues/11214#issuecomment-625669333

#### about cmake, can anyone remove the boost and test?

**Comment by oarsc** [comment]
I did comment the part using boost and it built correctly. I'm not in my pc anymore, so can't push it right now.

**Comment by nekiro** [comment]
Hmm, using g++10 breaks compilation of json somehow
I'm having this problem:
https://github.com/nlohmann/json/issues/2129

**Comment by mehah** [comment]
> 

Try gcc11 😁

**Comment by nekiro** [comment]
Yep, g++11 does compile fine, 1:1 branch code as of now.
Actually no, removing boost spawns linking errors xD
EDIT: nvm, i have 12 cores and make -j breaks compilation, so I have to use make -j 6 XD

**Review by nekiro — APPROVED** [review]

**Comment by nekiro** [comment]
Gotta update wiki after merge of this.

**Comment by mehah** [comment]
> Gotta update wiki after merge of this.

I have already updated vcpkg libs on windows

**Comment by nekiro** [comment]
> > Gotta update wiki after merge of this.
> 
> I have already updated vcpkg libs on windows

ubuntu is updated too

**Pull request merged**
