### PR TITLE
fix: walking issue #560

### PR DESCRIPTION
**Pull request by mehah**

### CODE REVIEW

**Comment by LeoTKBR** [comment]
@mehah 
this was the result, the stopped running bug was fixed but it seems to be stuck before going to the second step, follow the attached gif

GIF:
https://imgur.com/WWq41w4

**Comment by mehah** [comment]
@LeoTKBR 
try now

**Comment by LeoTKBR** [comment]
> @LeoTKBR try now

@mehah it hasn't changed, it's still giving the same result as before

**Comment by mehah** [comment]
@LeoTKBR
try again :D

**Comment by LeoTKBR** [comment]
@mehah 

This was the result, it seems that the part that is "tangled" was corrected, however, it has spasms in the outfit

GIF:
https://imgur.com/P0PVTfa

**Comment by mehah** [comment]
@LeoTKBR 
test again, unfortunately I can not test, this only occurs in your client.

**Comment by LeoTKBR** [comment]
> @LeoTKBR test again, unfortunately I can not test, this only occurs in your client.
@mehah 
it still has a problem apparently the result of screwing it was removed however a problem returned when going up the stairs the next step is invisible and the character is in the previous square and when going up the stairs from another position it is stuck as in the GIF attached, I decided to upload it the changes in a commit where only mine was changed (src) of course there are some other changes and I also updated in its most recent version so the 55 differences that's it I ended up forgetting to update the fork before creating the branch.

Commit:
https://github.com/LeoTKBR/otclient-mehah/commit/4f0ac3efeabfffd7d9a918a5b4e079b333daa31f

GIF:
Walking-Fix

**Comment by mehah** [comment]
there really is nothing else to do, if I don't have an environment where I can simulate the problem, I can't fix it, this is a specific problem with your sprite/client.

**Comment by LeoTKBR** [comment]
> there really is nothing else to do, if I don't have an environment where I can simulate the problem, I can't fix it, this is a specific problem with your sprite/client.

this is strange because as much as it is "different" it follows the same pattern as an 8.6 outfit with 3 sprites for each direction counting the stopped direction, that is the same result would happen on an 8.6 server or that uses the same amount of sprites per outfit....

**Comment by mehah** [comment]
> > there really is nothing else to do, if I don't have an environment where I can simulate the problem, I can't fix it, this is a specific problem with your sprite/client.
> 
> this is strange because as much as it is "different" it follows the same pattern as an 8.6 outfit with 3 sprites for each direction counting the stopped direction, that is the same result would happen on an 8.6 server or that uses the same amount of sprites per outfit....

yeah, but it's working as it should for 7.2, 8.6, 1098 and 12xx

**Comment by LeoTKBR** [comment]
> yeah, but it's working as it should for 7.2, 8.6, 1098 and 12xx

Are you sure about that, I'll take a base 8.6 0.4 and confirm and return with the results

**Comment by LeoTKBR** [comment]
@mehah 
this was the result of an 8.6 server in this case I will attach its source below

GIF:
TibiaWalking

Source:
https://forums.otserv.com.br/index.php?/forums/topic/169504-%C2%A0teamwarot-hardcore-86-team-vs-team/

**Comment by mehah** [comment]
now i understand, because i know tibia sprites and yours no, this problem started to happen in this PR, i will check here.

**Comment by mehah** [comment]
@LeoTKBR 
test

**Comment by mehah** [comment]
@LeoTKBR 
try again

**Comment by LeoTKBR** [comment]
@mehah 
Well, even though visually it is tangled, it is smooth on the floor now the question is if this is normal or do you still need to make some adjustments to correct it

GIF:
Walking-Fix

**Comment by mehah** [comment]
@LeoTKBR 
you tested it on 8.6, if this problem didn't occur, then it's something on your server, probably the formula.

**Pull request merged**
