### PR TITLE
Fix Encryption by default + adds switch to disable encrypting if desired

### PR DESCRIPTION
**Pull request by themaoci**
- added to use by default ENCRYPTION_PASSWORD if nothing specified
- added ENABLE_ENCRYPTION_BUILDER so you can just disable encryption builder
- fixed typo in main.cpp

# Description

nothing much to tell, you can do --encrypt without specifying a password then program will use internally specified password, also changed the typo that was hurting my eyes "OTCLient" xD

### CODE REVIEW

**Comment by mehah** [comment]
update the readme explaining what the ENABLE ENCRYPTION BUILDER is for, thx.

**Comment by themaoci** [comment]
> update the readme explaining what the ENABLE ENCRYPTION BUILDER is for, thx.

not sure what else i need  to add 
when you set ENABLE_ENCRYPTION it enables encryption in whole engine as it was b4. And now i also added ENABLE_ENCRYPTION_BUILDER which is located in main.cpp file only and it cuts out the part that uses --encrypt command so you can supply it outside without this option enabled / exposed in main function

**Comment by mehah** [comment]
@themaoci 
yes, I understand what ENABLE_ENCRYPTION_BUILDER is for, the problem is that some people won't know, so you need to leave it very detailed in the readme, if not, they'll end up opening an issue.****

**Comment by themaoci** [comment]
ehhh i added wrong commit... well will also add the comments in config.h near the options so ppl will know what to chosoe and when

**Pull request merged**
