### PR TITLE
Removed thread.h file

### PR DESCRIPTION
**Pull request by mehah**
someone with linux could test?

### CODE REVIEW

**Comment by oarsc** [comment]
I'm getting this error
```sh
$ make

[  0%] Building CXX object CMakeFiles/otclient.dir/src/framework/luafunctions.cpp.o
In file included from ./otclient/src/framework/../framework/core/graphicalapplication.h:29,
                 from ./otclient/src/framework/../framework/core/application.h:76,
                 from ./otclient/src/framework/luafunctions.cpp:23:
./otclient/src/framework/../framework/graphics/declarations.h:70:22: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   70 | using PoolPtr = std::shared_ptr<Pool>;
      |                      ^~~~~~~~~~
./otclient/src/framework/../framework/graphics/declarations.h:1:1: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
  +++ |+#include <memory>
    1 | /*
./otclient/src/framework/../framework/graphics/declarations.h:71:28: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
   71 | using PoolFramedPtr = std::shared_ptr<FramedPool>;
      |                            ^~~~~~~~~~
./otclient/src/framework/../framework/graphics/declarations.h:71:23: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
   71 | using PoolFramedPtr = std::shared_ptr<FramedPool>;
      |                       ^~~
In file included from ./otclient/src/framework/../framework/core/application.h:76,
                 from ./otclient/src/framework/luafunctions.cpp:23:
./otclient/src/framework/../framework/core/graphicalapplication.h:92:5: error: ‘PoolFramedPtr’ does not name a type
   92 |     PoolFramedPtr m_foregroundFramed;
      |     ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/otclient.dir/build.make:90: CMakeFiles/otclient.dir/src/framework/luafunctions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/otclient.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

**Comment by nekiro** [comment]
```#include <memory>```
in pch.h helps?

**Comment by oarsc** [comment]
> `#include <memory>`

Helps fixing that bug, now I'm getting
```sh
[  7%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/asyncdispatcher.cpp.o
In file included from ./src/framework/core/asyncdispatcher.cpp:23:
./src/framework/core/asyncdispatcher.h:58:10: error: ‘list’ in namespace ‘std’ does not name a template type
   58 |     std::list<std::function<void()>> m_tasks;
      |          ^~~~
./src/framework/core/asyncdispatcher.h:27:1: note: ‘std::list’ is defined in header ‘<list>’; did you forget to ‘#include <list>’?
   26 | #include <future>
  +++ |+#include <list>
   27 | 
./src/framework/core/asyncdispatcher.h:59:10: error: ‘list’ in namespace ‘std’ does not name a template type
   59 |     std::list<std::thread> m_threads;
      |          ^~~~
./src/framework/core/asyncdispatcher.h:59:5: note: ‘std::list’ is defined in header ‘<list>’; did you forget to ‘#include <list>’?
   59 |     std::list<std::thread> m_threads;
      |     ^~~
./src/framework/core/asyncdispatcher.h: In member function ‘std::shared_future<typename std::invoke_result<F>::type> AsyncDispatcher::schedule(const F&)’:
./src/framework/core/asyncdispatcher.h:42:9: error: ‘m_tasks’ was not declared in this scope; did you mean ‘task’?
   42 |         m_tasks.push_back([=]() { prom->set_value(task()); });
      |         ^~~~~~~
      |         task
./src/framework/core/asyncdispatcher.h: In member function ‘void AsyncDispatcher::dispatch(std::function<void()>)’:
./src/framework/core/asyncdispatcher.h:50:9: error: ‘m_tasks’ was not declared in this scope
   50 |         m_tasks.push_back(f);
      |         ^~~~~~~
./src/framework/core/asyncdispatcher.cpp: In member function ‘void AsyncDispatcher::terminate()’:
./src/framework/core/asyncdispatcher.cpp:35:5: error: ‘m_tasks’ was not declared in this scope
   35 |     m_tasks.clear();
      |     ^~~~~~~
./src/framework/core/asyncdispatcher.cpp: In member function ‘void AsyncDispatcher::spawn_thread()’:
./src/framework/core/asyncdispatcher.cpp:41:5: error: ‘m_threads’ was not declared in this scope
   41 |     m_threads.emplace_back([this] { exec_loop(); });
      |     ^~~~~~~~~
./src/framework/core/asyncdispatcher.cpp: In member function ‘void AsyncDispatcher::stop()’:
./src/framework/core/asyncdispatcher.cpp:50:32: error: ‘m_threads’ was not declared in this scope; did you mean ‘thread’?
   50 |     for (std::thread& thread : m_threads)
      |                                ^~~~~~~~~
      |                                thread
./src/framework/core/asyncdispatcher.cpp:52:5: error: ‘m_threads’ was not declared in this scope
   52 |     m_threads.clear();
      |     ^~~~~~~~~
./src/framework/core/asyncdispatcher.cpp: In member function ‘void AsyncDispatcher::exec_loop()’:
./src/framework/core/asyncdispatcher.cpp:59:16: error: ‘m_tasks’ was not declared in this scope
   59 |         while (m_tasks.empty() && m_running)
      |                ^~~~~~~
./src/framework/core/asyncdispatcher.cpp:65:38: error: ‘m_tasks’ was not declared in this scope; did you mean ‘task’?
   65 |         std::function<void()> task = m_tasks.front();
      |                                      ^~~~~~~
      |                                      task
make[2]: *** [CMakeFiles/otclient.dir/build.make:230: CMakeFiles/otclient.dir/src/framework/core/asyncdispatcher.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/otclient.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

**Comment by nekiro** [comment]
Here you go I fixed the missing includes

**Comment by oarsc** [comment]
Now it's building just fine 👍🏼

**Review by nekiro — APPROVED** [review]

**Review by oarsc — APPROVED** [review]
If @mehah sees ok those last changes we can merge this ;)

**Pull request merged**
