### PR TITLE
fix: clean cache + Change language in options

### PR DESCRIPTION
**Pull request by InnerCircleTFS**
konfiguracja

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### **Actual**

Do this and that doesn't happens

### **Expected**

Do this and that happens

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by kokekanon** [comment]
@InnerCircleTFS  add the prefix improve or fix


check 
change language if player is online
image

**Comment by InnerCircleTFS** [comment]
There are several errors in the project related to onInit, onTerminate, when reloading all the modules (when I am online). The biggest problem is in the game interface. I couldn't find the error, so I did this:
```
     @onClick: |
        if g_game.isOnline() then
          g_logger.warning("To prevent errors, change the language while offline." )
        else
          modules.client_locales.createWindow()
        end
```
I noticed an error in the function Controller:terminate(). I believe that self:onTerminate() should be after onGameEnd and not before. 

In terminate, I clean a variable, later in onGameEnd, I could use that variable. (This only applies when reloading).


```
function Controller:terminate()
    if self.onTerminate then
        self:onTerminate()
    end

    if self.onGameStart then
        disconnect(g_game, { onGameStart = self.onGameStart })
    end

    if self.onGameEnd then
        if g_game.isOnline() then self:onGameEnd() end
        disconnect(g_game, { onGameEnd = self.onGameEnd })
    end

```

**Comment by mehah** [comment]
@InnerCircleTFS
About the controller bug, thanks, but if you want, you can open a PR, I will accept it with pleasure, we don't have much bureaucracy here. :)

**Comment by mehah** [comment]
@InnerCircleTFS 
is done?

**Comment by InnerCircleTFS** [comment]
yes

**Pull request merged**
