### PR TITLE
feat: Task Module

### PR DESCRIPTION
**Pull request by dewral**
Free task module made by @rookgaard
A little edited by @Tofame

https://i.imgur.com/q6xTZHS.png

### CODE REVIEW

**Comment by mehah** [comment]
this module was developed from otv8, have you tested this client? thx

**Comment by dewral** [comment]
> this model was developed from otv8, have you tested this client? thx

Tbh no, @tofame was using this on mehah so i suppose it's working.
Ask him better cus not sure if there was any changes needed

**Comment by kokekanon** [comment]
I quickly tested
**From an OTC mehah point of view IT DOES work** 



> from TFS point of view,
> Test in nekiro 1.5
> 
> I'm not sure but I have the impression that:
> 
> once you finish a task you can repeat it,
> the tasks only gives experience.
> "itemRewards = {}" not implemented
> but I suppose that everyone can improve it to their liking from their server
> 
> but that is a separate topic, is problem of tfs and not of otc

**Comment by dewral** [comment]
> I quickly tested
> 
> **From an OTC mehah point of view IT DOES work** 
> 
> 
> 
> 
> 
> 
> 
> > from TFS point of view,
> 
> > Test in nekiro 1.5
> 
> > 
> 
> > I'm not sure but I have the impression that:
> 
> > 
> 
> > once you finish a task you can repeat it,
> 
> > the tasks only gives experience.
> 
> > "itemRewards = {}" not implemented
> 
> > but I suppose that everyone can improve it to their liking from their server
> 
> > 
> 
> > but that is a separate topic, is problem of tfs and not of otc

The item reward was changed for task points as far as i remember. I think i didnt add the code to handle that

**Pull request merged**
