### PR TITLE
fix: [new-layout] Add Pvp Mode + fix: chase and fight

### PR DESCRIPTION
**Pull request by kokekanon**
test in:
- **tfs** otland 13.10 main repo 
- **OTC** main repo          **vs**  3.5 release

theoretically functional, send the correct package.
## not yet approved until someone tests it

I don't know how to testify that.
I could only compare the 3.5 packet vs main repo packet 

bfdgdf

image
-----------
image

fix:
https://github.com/mehah/otclient/issues/794
https://github.com/opentibiabr/canary/issues/2736

ezgif-3-439606a248

TFS 13.10

```cpp
void ProtocolGame::parseFightModes(NetworkMessage& msg)
{
	uint8_t rawFightMode = msg.getByte();  // 1 - offensive, 2 - balanced, 3 - defensive
	uint8_t rawChaseMode = msg.getByte();  // 0 - stand while fighting, 1 - chase opponent
	uint8_t rawSecureMode = msg.getByte(); // 0 - can't attack unmarked, 1 - can attack unmarked
	uint8_t rawPvpMode = msg.getByte(); // pvp mode introduced in 10.0

	fightMode_t fightMode;
	if (rawFightMode == 1) {
		fightMode = FIGHTMODE_ATTACK;
	} else if (rawFightMode == 2) {
		fightMode = FIGHTMODE_BALANCED;
	} else {
		fightMode = FIGHTMODE_DEFENSE;
	}

	std::cout << "/////////////////////////////////////// " << std::endl;
	std::cout << "FightMode: " << static_cast<int>(fightMode) << std::endl;
	std::cout << "ChaseMode: " << static_cast<int>(rawChaseMode) << std::endl;
	std::cout << "SecureMode: " << static_cast<int>(rawSecureMode) << std::endl;
	std::cout << "PvpMode: " << static_cast<int>(rawPvpMode) << std::endl;
	std::cout << "/////////////////////////////////////// " << std::endl;
```

### CODE REVIEW

**Comment by rodrigopaixaorj** [comment]
Did you tested with minimized inventory ?
Also, when minimized, you can check/select DontChase and ChaseOpponent at the same time, this is wrong...
Unfortunately, I can't test right now, because I'm on my job

**Comment by kokekanon** [comment]
vvv

**Comment by rodrigopaixaorj** [comment]
@luanluciano93 @majestyotbr can you test ?

**Comment by majestyotbr** [comment]
Tested, it's working with Canary.

**Review by majestyotbr — APPROVED** [review]

**Pull request merged**
