### PR TITLE
improve: smooth walk

### PR DESCRIPTION
**Pull request by mehah**

### CODE REVIEW

**Comment by nekiro** [comment]
Seems that the walking broke, sometimes I can take few diagonal steps in a row, sometimes my character stops when taking turns for more time than he should. The issue with rendering from #918 still happens too.

**Comment by mehah** [comment]
@nekiro 
test again, now I think it's good, if it's shaking, it will be very little compared to the old one.

note: I tested with 1098 and 1340, vsync with 144hz and no-vsync without limited fps
unfortunately I don't have an environment with server 772 and 860.

**Comment by nekiro** [comment]
> @nekiro test again, now I think it's good, if it's shaking, it will be very little compared to the old one.
> 
> note: I tested with 1098 and 1340, vsync with 144hz and no-vsync without limited fps unfortunately I don't have an environment with server 772 and 860.

Now the walk lags when turning, diagonals seem to be ok.
About the shaking, no change, you can see it best with antialiasing set to none. You can still see items twitching on screen when you walk.
Also map click seems to be kinda teleporting now.
I think it's a painter issue, not the step duration/walk calculation

**Comment by mehah** [comment]
@nekiro,

Try out the walk, I think it's better than what you'll find in the main branch.

About the shaking, I could only reproduce it by manually limiting the FPS, it doesn't happen with vsync.

Since I rewrote a lot of things, I just need you to confirm that it's working as expected. We'll try to resolve this in another PR.

**Comment by nekiro** [comment]
Arrow walking seems ok, map click still "teleports" and there is weird lag after first step

https://github.com/user-attachments/assets/442388a6-39c2-4c5c-9cd6-364165a079fc

**Comment by mehah** [comment]
@nekiro 
what is your protocol? I can't reproduce this "teleport".

https://github.com/user-attachments/assets/4b3f33e2-1ffd-4f2d-8240-c169e99554ef

------------------------------------------------
try again, maybe I fixed it without realizing it.

**Review by nekiro — APPROVED** [review]
yep, its working fine, it seems it was my bad with the step duration calculation (I got some custom changes and it conflicted)

**Pull request merged**
