### PR TITLE
Fix github actions, cmake rework and integrate with vcpkg and improvement on protobuf

### PR DESCRIPTION
**Pull request by dudantas**
## Complete Cmake Rework, modernized the code so that you can work with GHA.

# Removed:
* VCPKG Build
* Removed generated Files from file .gitignore (all build files are required for Cmake cache generation)
* Lib Lua5.1 was removed and maintained only Luajit (faster and better)
* Removed the "consoleapplication" file
* Removed the "lbitlib" file, after all, if the idea is the project to use updated Libs, why do we want files that bring compatibility to old Libs? I just updated the files to use the functions of the new LIBs

# Modified:
* The metadata of the Bitwise functions have been changed, now being in place of "bit32." is
"bit."
* Protobuf will now be chased along with the client build, avoiding random errors related to Protobuf's version is different from the compiled file (this way, no matter if the repository file is outdated, as a new one will always be generated in a compilation from rebuild all)
* Modified the structure of some folders, such as "protobuf" and "cmake" folder, "protobuf" was sent to the src main folder and "cmake" to the client main folder
* Namespace protobuf changed from "tibia" to "otclient"
* Merged the files of the Protobuf "shared.proto and appearances.proto" in one (appearances)

# Added:
* Issue Template
* Pull Request Template
* Pull Request Labeller
* Check to inform that clang is not supported (it is possible to use docker on mac, this way we avoid headaches related to support for an OS that is practically not used)
## GHA:
* Codacy
* CodeQL
* Review dog
* SonarCloud
* Build docker
* Build Ubuntu
* Build Windows
## Cmake:
* Cmakepresets
* VCPKG Manifest
* Otcicon
## Client:
* Added the functions LuaInterface::registerTable and LuaInterface::registerMethod and Bitwise Functions (if necessary at some point compatibility with the Lua 5.1)

Note: Some checks are failing as they should only work after the merge, they should be ignored, the main ones are ok

Thanks for @costallat to help with gha and cmake build.

### CODE REVIEW

**Comment by soul4soul** [comment]
It would be great to have the actions save the compiled windows executable as artifacts.

**Comment by gaamelu** [comment]
What is missing to finish this update?

**Comment by dudantas** [comment]
> It would be great to have the actions save the compiled windows executable as artifacts.

It's a great positive point, it will be that it will prevent the Linux Quebre build (for those who develop in Windows, like me).

Pull is ready, we intend to give merge this soon.

**Comment by dudantas** [comment]
> What is missing to finish this update?

Is finished, some adjustments were missing, we made it in the last few days, today we are going to merge!

**Review by beats-dh — APPROVED** [review]

**Pull request merged**
