### PR TITLE
build: use conditional sound libs for compiling on newer linux distros

### LINKED ISSUE #753: Linux Compile Issue
### Priority

Medium

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [X] Other

### What happened?

Was following the Compiling on Arch Linux guide. Current issue is 
```
-- Enabled: ipo
-- Found Protobuf Compiler: /usr/bin/protoc
FATAL_ERROR,Failed to generate protobuf files
-- Bot protection: ON
-- Use precompiled header: ON
-- Enabled: Build unity for speed up compilation
-- Disabled: asan
-- Disabled: DEBUG LOG
-- Build type: 
-- Build commit: 
-- Build revision: 
CMake Deprecation Warning at /usr/lib/cmake/OpenAL/OpenALConfig.cmake:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  src/CMakeLists.txt:217 (find_package)


CMake Error at src/CMakeLists.txt:219 (find_package):
  Could not find a package configuration file provided by "Vorbis" with any
  of the following names:

    VorbisConfig.cmake
    vorbis-config.cmake

  Add the installation prefix of "Vorbis" to CMAKE_PREFIX_PATH or set
  "Vorbis_DIR" to a directory containing one of the above files.  If "Vorbis"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```
when trying to run cmake . -B build

I installed all the required dependency packages but ran into a couple missing dependencies.
Ran

- pacman -S asio
- yay -S stduuid
- yay -S cpp-httplib

to fix the previous errors where it couldn't find those packages, but libvorbis is in the guide already, and tried reinstalling it as well. I know just enough about Arch Linux to get in trouble, and I don't know why this isn't working.

Also the src/framework/protobuf/proto/ doesn't seem to exist in the current repo, but I found src/protobuf/ with a generate.sh in it, and just ran that. Not sure if that is why it is also getting the Fatal_ERROR, Failed to generate protobuf files.

Please let me know if I need to provide more information.

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tornadia**
# Description

Fixes compiling on Ubuntu with disabled sound
- Doesn't fix https://github.com/mehah/otclient/issues/753 but helps compile w/o sound.

### **Actual**

Doesnt compile if sound is used

### **Expected**

Makes it possible to disable sound again

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

  - [ ] Test A
  - [ ] Test B

**Test Configuration**:

  - Server Version:
  - Client:
  - Operating System:

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by mehah** [comment]
@tornadia 
build is broken.

**Comment by mehah** [comment]
@tornadia 
which has leading or trailing whitespace.  This is
    now an error according to policy CMP0004.

**Comment by mehah** [comment]
@tornadia 
https://github.com/mehah/otclient/actions/runs/9700179052/job/26783002143?pr=781#step:8:371


image

**Comment by tornadia** [comment]
> @tornadia https://github.com/mehah/otclient/actions/runs/9700179052/job/26783002143?pr=781#step:8:371

Hi Mehah! I appreciate your thorough reviews to push this effort further and get it merged. I am planning to resolve the issue by removing the quotation marks and maybe separating the setters into different lines further if that doesn't work. In my local environment it is working fine. Can you suggest an approach to resolve this?

**Comment by mehah** [comment]
@tornadia 
From what I understand, these errors are syntax errors, I'll see if @dudantas or @beats-dh can help you.

**Comment by mehah** [comment]
https://github.com/mehah/otclient/pull/923

**Pull request closed without merging**
