### PR TITLE
Fix build for Mac

### LINKED ISSUE #297: [request] The macOS support
### Priority

Enhancement

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

Hi,

Do you plan add macOS support?

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tuliomagalhaes**
# Description
Resolve #297
Fix build for Mac OSX

### **Actual**

It does not compile to Mac devices.

### **Expected**

Compile to Mac devices.

## Fixes

\# (issue)

## Type of change

Please delete options that are not relevant.

  - [x] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [x] This change requires a documentation update

## How Has This Been Tested

Compiling the project on Mac Intel and Apple M1.

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by mehah — APPROVED** [review]

**Comment by nekiro** [comment]
I tried compiling on macos recently, so I will be more than happy to test this, any instructions for installing required libs?

**Comment by tuliomagalhaes** [comment]
> I tried compiling on macos recently, so I will be more than happy to test this, any instructions for installing required libs?

Just create the regular build folder and then run the `cmake ..` from it and then run `make`. All libs are provided by vcpkg when running the cmake.

**Comment by nekiro** [comment]
> > I tried compiling on macos recently, so I will be more than happy to test this, any instructions for installing required libs?
> 
> Just create the regular build folder and then run the `cmake ..` from it and then run `make`. All libs are provided by vcpkg when running the cmake.

Nah, that won't work. Running cmake yields fail when finding nlohmann-json library (it fails to find it)

**Comment by tuliomagalhaes** [comment]
> > > I tried compiling on macos recently, so I will be more than happy to test this, any instructions for installing required libs?
> > 
> > 
> > Just create the regular build folder and then run the `cmake ..` from it and then run `make`. All libs are provided by vcpkg when running the cmake.
> 
> Nah, that won't work. Running cmake yields fail when finding nlohmann-json library (it fails to find it)

Hmmm.. that’s weird.. what are your specs ?

**Comment by nekiro** [comment]
> > > > I tried compiling on macos recently, so I will be more than happy to test this, any instructions for installing required libs?
> > > 
> > > 
> > > Just create the regular build folder and then run the `cmake ..` from it and then run `make`. All libs are provided by vcpkg when running the cmake.
> > 
> > 
> > Nah, that won't work. Running cmake yields fail when finding nlohmann-json library (it fails to find it)
> 
> Hmmm.. that’s weird.. what are your specs ?

I'm running macos monterey 12.6, with homebrew, cmake installed thru `brew install cmake` on Macbook Pro m1 14" (2021)

**Comment by tuliomagalhaes** [comment]
> > > > > I tried compiling on macos recently, so I will be more than happy to test this, any instructions for installing required libs?
> > > > 
> > > > 
> > > > Just create the regular build folder and then run the `cmake ..` from it and then run `make`. All libs are provided by vcpkg when running the cmake.
> > > 
> > > 
> > > Nah, that won't work. Running cmake yields fail when finding nlohmann-json library (it fails to find it)
> > 
> > 
> > Hmmm.. that’s weird.. what are your specs ?
> 
> I'm running macos monterey 12.6, with homebrew, cmake installed thru `brew install cmake` on Macbook Pro m1 14" (2021)

Can you upgrade your vcpkg and try again to post the error here ?

**Comment by nekiro** [comment]
Vcpkg doesn't even seem to be called, it fails at the part where finding libs is required in cmake, so it fails before vcpkg even installs libs and links them.

I have protobuf installed thru brew (probably something else used it as dep), it would probably fail with protobuf finding error if it wasn't installed.

Console output:
```nekiro@Marcins-MacBook-Pro build % cmake ..
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Enabled: ipo
-- Found Protobuf: /opt/homebrew/lib/libprotobuf.dylib (found version "3.21.6") 
-- Found Protobuf Compiler: /opt/homebrew/bin/protoc
-- Bot protection: ON
-- Use precompiled header: OFF
-- Disabled: asan
-- Disabled: DEBUG LOG
-- Build type: 
-- Build commit: 
-- Build revision: 
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd  
-- Looking for lzma_auto_decoder in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/liblzma.tbd
-- Looking for lzma_auto_decoder in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/liblzma.tbd - found
-- Looking for lzma_easy_encoder in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/liblzma.tbd
-- Looking for lzma_easy_encoder in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/liblzma.tbd - found
-- Looking for lzma_lzma_preset in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/liblzma.tbd
-- Looking for lzma_lzma_preset in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/liblzma.tbd - found
-- Found LibLZMA: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/liblzma.tbd (found version "5.2.6") 
CMake Error at src/CMakeLists.txt:173 (find_package):
  By not providing "Findnlohmann_json.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "nlohmann_json", but CMake did not find one.

  Could not find a package configuration file provided by "nlohmann_json"
  with any of the following names:

    nlohmann_jsonConfig.cmake
    nlohmann_json-config.cmake

  Add the installation prefix of "nlohmann_json" to CMAKE_PREFIX_PATH or set
  "nlohmann_json_DIR" to a directory containing one of the above files.  If
  "nlohmann_json" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/Users/nekiro/Documents/repos/nme/build/CMakeFiles/CMakeOutput.log".
See also "/Users/nekiro/Documents/repos/nme/build/CMakeFiles/CMakeError.log".
nekiro@Marcins-MacBook-Pro build % 
```

Cmake output and error log.
[CMakeOutput.log](https://github.com/mehah/otclient/files/9693670/CMakeOutput.log)
[CMakeError.log](https://github.com/mehah/otclient/files/9693669/CMakeError.log)

**Comment by tuliomagalhaes** [comment]
> Vcpkg doesn't even seem to be called, it fails at the part where finding libs is required in cmake, so it fails before vcpkg even installs libs and links them.
> I have protobuf installed thru brew (probably something else used it as dep), it would probably fail with protobuf finding error if it wasn't installed.

hmm... I think you are missing the compilers, try to install xcode using App Store and try again, I'm not sure if it's possible to install the compiler and toolchains without downloading XCode.

PS: You can download just the `Command Line Tools for Xcode` using Apple Developer portal.

**Comment by nekiro** [comment]
> > Vcpkg doesn't even seem to be called, it fails at the part where finding libs is required in cmake, so it fails before vcpkg even installs libs and links them.
> > I have protobuf installed thru brew (probably something else used it as dep), it would probably fail with protobuf finding error if it wasn't installed.
> 
> hmm... I think you are missing the compilers, try to install xcode using App Store and try again, I'm not sure if it's possible to install the compiler and toolchains without downloading XCode.
> 
> PS: You can download just the `Command Line Tools for Xcode` using Apple Developer portal.

I do have compiler and command line tools. I developed expo (react native) apps before and xcode / command line tools is mandatory.

~~I also tried to compile macos myself and I managed to link it properly with adding additional cmake preset and installing libs thru brew, only then they are found properly in cmake, otherwise no, because cmake -- build installs vcpkg libs after cmake files are generated. It should install libs before doing that I believe or we are missing some .cmake files to find these libs like the other pr (https://github.com/mehah/otclient/pull/299) with FindAsio which fixes finding asio on macos.~~

Edit: OK I managed to call vcpkg to install libs, vcpkg depends on where vcpkg is installed
proper command:
`cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake`
from root directory of otclient.

Looks like maocs build isnt running generation on protobuf too.
```
CMake Error at /Users/nekiro/vcpkg/scripts/buildsystems/vcpkg.cmake:582 (_add_executable):
  Cannot find source file:

    protobuf/appearances.pb.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  src/CMakeLists.txt:82 (add_executable)


CMake Error at /Users/nekiro/vcpkg/scripts/buildsystems/vcpkg.cmake:582 (_add_executable):
  No SOURCES given to target: otclient
Call Stack (most recent call first):
  src/CMakeLists.txt:82 (add_executable)
  ```

**Review by nekiro — APPROVED** [review]
Besides protobuf_generate_cpp not working at all on macos for some reason. I didn't find yet why, this pr properly fixes compilation from source side

I'll update wiki to provide compilation instructions after this gets merged,

**Comment by tuliomagalhaes** [comment]
> Besides protobuf_generate_cpp not working at all on macos for some reason. I didn't find yet why, this pr properly fixes compilation from source side
> 
> I'll update wiki to provide compilation instructions after this gets merged,



> > > Vcpkg doesn't even seem to be called, it fails at the part where finding libs is required in cmake, so it fails before vcpkg even installs libs and links them.
> > > I have protobuf installed thru brew (probably something else used it as dep), it would probably fail with protobuf finding error if it wasn't installed.
> > 
> > 
> > hmm... I think you are missing the compilers, try to install xcode using App Store and try again, I'm not sure if it's possible to install the compiler and toolchains without downloading XCode.
> > PS: You can download just the `Command Line Tools for Xcode` using Apple Developer portal.
> 
> I do have compiler and command line tools. I developed expo (react native) apps before and xcode / command line tools is mandatory.
> 
> ~I also tried to compile macos myself and I managed to link it properly with adding additional cmake preset and installing libs thru brew, only then they are found properly in cmake, otherwise no, because cmake -- build installs vcpkg libs after cmake files are generated. It should install libs before doing that I believe or we are missing some .cmake files to find these libs like the other pr (#299) with FindAsio which fixes finding asio on macos.~
> 
> Edit: OK I managed to call vcpkg to install libs, vcpkg depends on where vcpkg is installed proper command: `cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake` from root directory of otclient.
> 
> Looks like maocs build isnt running generation on protobuf too.
> 
> ```
> CMake Error at /Users/nekiro/vcpkg/scripts/buildsystems/vcpkg.cmake:582 (_add_executable):
>   Cannot find source file:
> 
>     protobuf/appearances.pb.cc
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
>   .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
> Call Stack (most recent call first):
>   src/CMakeLists.txt:82 (add_executable)
> 
> 
> CMake Error at /Users/nekiro/vcpkg/scripts/buildsystems/vcpkg.cmake:582 (_add_executable):
>   No SOURCES given to target: otclient
> Call Stack (most recent call first):
>   src/CMakeLists.txt:82 (add_executable)
> ```

Can you upload the entire log again after running the vcpkg install manually?

**Comment by tuliomagalhaes** [comment]
Another thing that

> Besides protobuf_generate_cpp not working at all on macos for some reason. I didn't find yet why, this pr properly fixes compilation from source side
> 
> I'll update wiki to provide compilation instructions after this gets merged,

Another thing that is required to make it work and to add in our documentation is to install https://www.xquartz.org/

**Comment by nekiro** [comment]
> Another thing that
> 
> > Besides protobuf_generate_cpp not working at all on macos for some reason. I didn't find yet why, this pr properly fixes compilation from source side
> > I'll update wiki to provide compilation instructions after this gets merged,
> 
> Another thing that is required to make it work and to add in our documentation is to install https://www.xquartz.org/

I see no reason to post the whole cmake ouput again.
I debugged the issue and this:
https://github.com/mehah/otclient/blob/main/src/protobuf/CMakeLists.txt#L23

Doesn't do anything, it doesn't spit out generated protobuf nor it errors, so it success, but files aren't generated.
I tried to fix this with EXECUTE_PROCESS, but protoc is very dumb with absolute paths, thus it does output invalid relative path error.

**Comment by tuliomagalhaes** [comment]
> > Another thing that
> > > Besides protobuf_generate_cpp not working at all on macos for some reason. I didn't find yet why, this pr properly fixes compilation from source side
> > > I'll update wiki to provide compilation instructions after this gets merged,
> > 
> > 
> > Another thing that is required to make it work and to add in our documentation is to install https://www.xquartz.org/
> 
> I see no reason to post the whole cmake ouput again. I debugged the issue and this: https://github.com/mehah/otclient/blob/main/src/protobuf/CMakeLists.txt#L23
> 
> Doesn't do anything, it doesn't spit out generated protobuf nor it errors, so it success, but files aren't generated. I tried to fix this with EXECUTE_PROCESS, but protoc is very dumb with absolute paths, thus it does output invalid relative path error.

So weird that I don't have any clue on what is happening.

**Comment by nekiro** [comment]
> 

I think I solved it, I'll do a follow up pr

**Pull request merged**
