### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by mehah**
- ReSharper cleanup
- SQL Fw removed

### CODE REVIEW

**Review by nekiro — APPROVED** [review]

**Comment by oarsc** [comment]
I'm getting some building errors after this chage:
```
[  0%] Building CXX object CMakeFiles/otclient.dir/src/framework/luafunctions.cpp.o
In file included from ./src/framework/../framework/graphics/paintershaderprogram.h:27,
                 from ./src/framework/../framework/graphics/painter.h:28,
                 from ./src/framework/../framework/graphics/particletype.h:27,
                 from ./src/framework/../framework/graphics/particlemanager.h:27,
                 from ./src/framework/luafunctions.cpp:49:
./src/framework/../client/position.h: In member function ‘double Position::distance(const Position&) const’:
./src/framework/../client/position.h:202:74: error: no matching function for call to ‘pow<int32_t>(int, int)’
  202 |     double distance(const Position& pos) const { return sqrt(pow<int32_t>(pos.x - x, 2) + pow<int32_t>(pos.y - y, 2)); }
      |                                                              ~~~~~~~~~~~~^~~~~~~~~~~~~~
./src/framework/../client/position.h:202:103: error: no matching function for call to ‘pow<int32_t>(int, int)’
  202 |     double distance(const Position& pos) const { return sqrt(pow<int32_t>(pos.x - x, 2) + pow<int32_t>(pos.y - y, 2)); }
      |                                                                                           ~~~~~~~~~~~~^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/otclient.dir/build.make:90: CMakeFiles/otclient.dir/src/framework/luafunctions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/otclient.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

**Comment by mehah** [comment]
> I'm getting some building errors after this chage:

In position.h try swapping cmath for math.h

**Comment by oarsc** [comment]
```
./src/framework/net/protocol.cpp: In lambda function:
./src/framework/net/protocol.cpp:160:74: error: no match for call to ‘(const std::uniform_int_distribution<unsigned int>) (std::random_device&)’
  160 |     std::generate(m_xteaKey.begin(), m_xteaKey.end(), [&]() { return unif(rd); });
      |                                                                      ~~~~^~~~
In file included from /usr/include/c++/11/bits/stl_algo.h:66,
                 from /usr/include/c++/11/algorithm:62,
                 from /usr/include/asio/basic_streambuf.hpp:22,
                 from /usr/include/asio/streambuf.hpp:22,
                 from ./src/framework/net/connection.h:26,
                 from ./src/framework/net/protocol.h:26,
                 from ./src/framework/net/protocol.cpp:23:
/usr/include/c++/11/bits/uniform_int_dist.h:192:9: note: candidate: ‘std::uniform_int_distribution<_IntType>::result_type std::uniform_int_distribution<_IntType>::operator()(_UniformRandomBitGenerator&) [with _UniformRandomBitGenerator = std::random_device; _IntType = unsigned int; std::uniform_int_distribution<_IntType>::result_type = unsigned int]’ (near match)
  192 |         operator()(_UniformRandomBitGenerator& __urng)
      |         ^~~~~~~~
/usr/include/c++/11/bits/uniform_int_dist.h:192:9: note:   passing ‘const std::uniform_int_distribution<unsigned int>*’ as ‘this’ argument discards qualifiers
/usr/include/c++/11/bits/uniform_int_dist.h:197:9: note: candidate: ‘template<class _UniformRandomBitGenerator> std::uniform_int_distribution<_IntType>::result_type std::uniform_int_distribution<_IntType>::operator()(_UniformRandomBitGenerator&, const std::uniform_int_distribution<_IntType>::param_type&) [with _UniformRandomBitGenerator = _UniformRandomBitGenerator; _IntType = unsigned int]’
  197 |         operator()(_UniformRandomBitGenerator& __urng,
      |         ^~~~~~~~
/usr/include/c++/11/bits/uniform_int_dist.h:197:9: note:   template argument deduction/substitution failed:
./src/framework/net/protocol.cpp:160:74: note:   candidate expects 2 arguments, 1 provided
  160 |     std::generate(m_xteaKey.begin(), m_xteaKey.end(), [&]() { return unif(rd); });
      |                                                                      ~~~~^~~~

```

**Comment by mehah** [comment]
Remove const on unif variable

**Comment by oarsc** [comment]
Fixed ;)

**Pull request merged**
