### PR TITLE
[WIP] Protocol http/ws

### PR DESCRIPTION
**Pull request by alfuveam**
## HTTP protocol based on kondrah client

Now support HTTP/HTTPS/WS/WSS. 

### Available functions
```
HTTP.get(url, callback)
HTTP.getJSON(url, callback) -- website should return json
HTTP.post(url, data, callback)
HTTP.postJSON(url, data, callback) -- data should be a table {} and website should return json
HTTP.download(url, file, downloadCallback, progressCallback) -- progressCallback can be null
HTTP.downloadImage(url, downloadImageCallback)
HTTP.cancel(operationId)
```

Each function, except `cancel` return operationId, you can use it to cancel http request.
Those functions came from `modules/corelib/http.lua` and they use more advanced g_http API.
Files from download are available in virtual "/downloads" directory. Downloading of images is using cache based on url (so if you change image it won't refresh until restart or change url).

### Callbacks
For get, getJSON, post and postJSON HTTP callback should look like this:
```
function callback(data, err)
    if err then
        -- handle error, if err is not null then err is a string
        return 
    end
    -- handle data
    -- if it's data from getJSON/postJSON then data is a table {}
end
```

For download:
```
function downloadCallback(path, checksum, err)
    if err then
        -- handle error, if err is not null then err is a string
        return 
    end
    -- do something with path and checksum
end

function progressCallback(progress, speed)
    -- progress is from 0 to 100
    -- speed is in kbps
end
```

For downloadImage:
```
function downloadImageCallback(path, err)
    if err then
        -- handle error, if err is not null then err is a string
        return 
    end
    -- do something with path to downloaded image
end
```

### WebSocketServer 
```
// Node.js WebSocket server script
var WebSocketServer = require("ws").Server;
var WebSocket = require("ws").WebSocket;

var wss = new WebSocketServer({port:9898});

wss.on('connection', function connection(ws) {
  console.log("connection");
  ws.on('message', function message(data, isBinary) {
    wss.clients.forEach(function each(client) {
      if (client.readyState === WebSocket.OPEN) {
        client.send(data, { binary: isBinary });
      }
    });
  });

  ws.on('close', () => {
    console.log('User disconnected.')
  });  
});
```

### References
[1] -> https://datatracker.ietf.org/doc/html/rfc6455
[2] -> https://developer.mozilla.org/pt-BR/docs/Web/API/WebSockets_API/Writing_WebSocket_servers
[3] -> https://gitlab.com/eidheim/Simple-WebSocket-Server/-/blob/master/client_ws.hpp
[4] -> https://github.com/katzarsky/WebSocket
[5] -> https://think-async.com/Asio/asio-1.22.1/doc/
[6] -> https://github.com/OTCv8/otcv8-dev
[7] -> https://github.com/OTCv8/otcv8-tools/blob/main/tutorials/HTTP.md

### CODE REVIEW

**Comment by nekiro** [comment]
Fix login request for protocol 12 too

**Comment by mehah** [comment]
@alfuveam
any news?

**Comment by alfuveam** [comment]
Problems to solve

- [ ] [HTTP/S] Redirects
- [ ] [HTTP/S] Not working if server use cloudflare "sslv3 alert handshake failure"

**Comment by gesior** [comment]
> Problems to solve
> 
> * [ ]  [HTTP/S] Not working if server use cloudflare "sslv3 alert handshake failure"

Does not work at all if site is behine cloudflare or only when protection is enabled?
It's normal that you can't open `login.php` from client, if it's behind cloudflare and protection is enabled. It's same on official Tibia 12+ client. 12+ OTSes have special cloudflare config, to disable protection for login.php, if request type is POST and it contains JSON body.

If it always prints that error, it may be because for some reason OTC uses `sslv3`, which is not secure. It should negotiate protocol with server and use TLS 1.2+.

EDIT:
Maybe we got replace `asio::ssl::context::sslv23_client` with `asio::ssl::context::tls_client` or `asio::ssl::context::tlsv12_client`

**Comment by conde2** [comment]
@alfuveam

First I would like to thank you for opening this pull request.
I wonder how is the current status of this pull request? It is very impressive how far it was.

**Comment by alfuveam** [comment]
@nekiro fixed http protocol request to protocol 12

**Pull request closed without merging**
