### PR TITLE
improve: update vcpkg baseline

### PR DESCRIPTION
**Pull request by mehah**
in vcpkg folder:
git pull
vcpkg upgrade --no-dry-run

### CODE REVIEW

**Comment by OTArchive** [comment]
Abseil is no longer included with protobuf, it's now necessary to include it. You can see how I've done it for the browser version, but I'm not experienced. Please let me know if there's a better way.

**Review by nekiro — APPROVED** [review]

**Comment by mehah** [comment]
@OTArchive 
> Abseil is no longer included with protobuf, it's now necessary to include it. You can see how I've done it for the browser version, but I'm not experienced. Please let me know if there's a better way.

It says to put it in vcpkg.json?

Strange that protobuf was supposed to have put Abseil as a dependency, if that is really the problem.

**Comment by OTArchive** [comment]
> @OTArchive 
> > Abseil is no longer included with protobuf, it's now necessary to include it. You can see how I've done it for the browser version, but I'm not experienced. Please let me know if there's a better way.
> 
> It says to put it in vcpkg.json?
> 
> Strange that protobuf was supposed to have put Abseil as a dependency, if that is really the problem.

In my case I had to explicitly include it using CMakeLists so it could find the libs to link to. I did not use vcpkg.json though.

**Comment by OTArchive** [comment]
@mehah this is what I was talking about: https://github.com/OTArchive/otclient/commit/11e11f2c1646d317d016c4e43a6f1002be41a130
It's the same I did for the browser version to use the updated vcpkg.
It's not elegant, but it (mostly?) works:
https://github.com/OTArchive/otclient/actions/runs/11414774221/job/31764084809

https://github.com/OTArchive/otclient/actions/runs/11414632189

**Comment by mehah** [comment]
> @mehah this is what I was talking about: [OTArchive@11e11f2](https://github.com/OTArchive/otclient/commit/11e11f2c1646d317d016c4e43a6f1002be41a130) It's the same I did for the browser version to use the updated vcpkg. It's not elegant, but it (mostly?) works: https://github.com/OTArchive/otclient/actions/runs/11414774221/job/31764084809
> 
> https://github.com/OTArchive/otclient/actions/runs/11414632189

a questão que não sei nada de cmake, posso até colocar isso e vê se resolve.

**Comment by OTArchive** [comment]
> > @mehah this is what I was talking about: [OTArchive@11e11f2](https://github.com/OTArchive/otclient/commit/11e11f2c1646d317d016c4e43a6f1002be41a130) It's the same I did for the browser version to use the updated vcpkg. It's not elegant, but it (mostly?) works: https://github.com/OTArchive/otclient/actions/runs/11414774221/job/31764084809
> > https://github.com/OTArchive/otclient/actions/runs/11414632189
> 
> a questão que não sei nada de cmake, posso até colocar isso e vê se resolve.

Clonei seu repo e apliquei pra testar, resolveu em tudo menos windows-release-asan. O erro mudou, parece que essa build está tentando linkar com a dll do protobuf, ao invés da lib.

**Pull request merged**
