### PR TITLE
Fix black and red squares behaviors

### LINKED ISSUE #898: Attack square dissapears
### Priority

Low

### Area

- [ ] Data
- [ ] Source
- [ ] Docker
- [X] Other

### What happened?

Red attack square dissapears shortly after attacking a monster - The player still attacks the monster and the red square is visible on battle list, however u are unable to see the red attack square around monster.

https://gyazo.com/3fa4e59aeabaabd43aabfe35c0b04720 

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by OTArchive**
# Description

Black squares are not showing around attacking creatures, and the red target square disappears when you are attacked.

### **Expected**

Black squares on attacking creatures and red square when you are attacking.

## Fixes

**Please help me understand this so we can code a proper solution.**
In ProtocolGame::parseCreaturesMark, if I set "isPermanent" to false, the squares issues seem to get solved:

image

https://github.com/user-attachments/assets/b5e41862-78ba-4828-9da1-b16083513695

Canary and TFS always sends 0x01 for "isPermanent":
[Server side reference](https://github.com/opentibiabr/canary/blob/f2f52cc2c55fa1db77dfb35e844f5b3546b63008/src/server/network/protocol/protocolgame.cpp#L3397)

Am I missing something? Should squares always be timedSquares?

Fixes #898

### CODE REVIEW

**Comment by luanluciano93** [comment]
If the server sent: U32, U8 and U8, you must receive these bytes, even if you are not going to use them.

**Comment by OTArchive** [comment]
> If the server sent: U32, U8 and U8, you must receive these bytes, even if you are not going to use them.

Yeah, but any idea why the current implementation is broken? Should squares always be timedSquares?

**Comment by luanluciano93** [comment]
if the problem is in isPermanent, just receive the byte and don't define it in the variable:
```cpp
        msg->getU8();
        const bool isPermanent = false;
```
Anyway, it's interesting to test on an older version to see if the behavior is the same.

**Comment by OTArchive** [comment]
> if the problem is in isPermanent, just receive the byte and don't define it in the variable:
> 
> ```c++
>         msg->getU8();
>         const bool isPermanent = false;
> ```
> 
> Anyway, it's interesting to test on an older version to see if the behavior is the same.

Sure, but that would leave dead code, right?
You are right, we should look into older versions.

**Comment by OTArchive** [comment]
> If the server sent: U32, U8 and U8, you must receive these bytes, even if you are not going to use them.

Turns out that using the byte in Canary 13.40 breaks it again

8.6 server reference:
https://github.com/otservme/global860/blob/571183a2858e638d49778cca914c8126bd6f17ce/sources/protocolgame.cpp#L1613

**Review by luanluciano93 — APPROVED** [review]

**Pull request merged**
