### PR TITLE
Add User-Agent header to HTTP requests

### PR DESCRIPTION
**Pull request by rafaeru97**
- Added User-Agent header "Mozilla/5.0" to all HTTP requests in httplib::Headers.

# Description

Updated User-Agent to match the original Tibia 13 Client

### **Actual**

Some servers did not allow connections through OTC.

### **Expected**

Fixed connection issues with servers using User-Agent validation.

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I checked the PR checks reports
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings
  - [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by leoddias** [comment]
@delphinusryetropical 
This fix the issue https://github.com/mehah/otclient/issues/827 ?

**Comment by rafaeru97** [comment]
It connect to character list so i think it fix this issue.

https://i.imgur.com/PE843UC.gif

**Comment by delphinusryetropical** [comment]
> It connect to character list so i think it fix this issue.
> 
> https://i.imgur.com/PE843UC.gif

Your solution of adding the "Mozilla/5.0" User-Agent header has indeed resolved the immediate issue for some servers. 
This simple fix can be effective in many cases where servers perform basic User-Agent validation.
However, it's worth noting that there are more complex scenarios where additional headers or specific request formatting may be required. 
For instance, consider the following example:

REQUEST
```
POST https://www.gunzodus.net/game/login/1330?nservice.php HTTP/1.1
Host: www.gunzodus.net
Content-Type: application/json
Content-Disposition: form-data; name="metadata"
Content-Length: 89
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: pl-PL,en,*
User-Agent: Mozilla/5.0
{"email":"testtest1@test.test","password":"testtest1","stayloggedin":true,"type":"login"}
```
RESPONSE
```
{"session":{"sessionkey":"60c1e638dd08f78f20b7154131b0827d26dd5bfa","lastlogintime":0,"ispremium":true,"premiumuntil":4294967295,"status":"active","returnernotification":false,"showrewardnews":false,"isreturner":false,"fpstracking":false,"optiontracking":false,"tournamentticketpurchasestate":0,"tournamentcyclephase":0},"playdata":{"worlds":[{"id":0,"name":"Gunzodus","externaladdressprotected":"login.gunzodus.net","externalportprotected":7172,"previewstate":0,"location":"EUR","externaladdressunprotected":"unprotected.gunzodus.net","externalportunprotected":7175,"anticheatprotection":false,"pvptype":0,"istournamentworld":false,"restrictedstore":false}],"characters":[{"worldid":0,"name":"Test Test","ismale":false,"tutorial":false,"level":20,"vocation":"Sorcerer","outfitid":128,"headcolor":44,"torsocolor":128,"legscolor":44,"detailcolor":44,"addonflags":0,"ishidden":false,"ismaincharacter":true,"istournamentparticipant":false,"dailyrewardstate":0}]},"worlds":[{"id":0,"name":"Gunzodus","externaladdressprotected":"login.gunzodus.net","externalportprotected":7172,"previewstate":0,"location":"EUR","externaladdressunprotected":"unprotected.gunzodus.net","externalportunprotected":7175,"anticheatprotection":false,"pvptype":0,"istournamentworld":false,"restrictedstore":false}]}
```

In this case, the server expects a specific set of headers and a particular request format. 
When sent correctly, it returns a detailed JSON response with session and character information.
However, when the same request is sent through OTClient, even with the User-Agent header, it may still result in an error:

```
POST /game/login/1330?nservice.php
{"email":"testtest1@test.test","password":"testtest1","stayloggedin":true,"type":"login"}
Accept: */*
Connection: close
Content-Length: 89
Content-Type: application/json
Host: www.gunzodus.net
User-Agent: Mozilla/5.0

Response:
HTTP/1.1 200 OK
{"errorCode":3,"errorMessage":"Account login or password is not correct."}
```

**Comment by luanluciano93** [comment]
I was having problems logging into znote's login.php because of this. Solved here, thank you!

Resolves the issue reported in #717

**Review by luanluciano93 — APPROVED** [review]

**Pull request merged**
