### PR TITLE
fix: botserver updates

### PR DESCRIPTION
**Pull request by rodrigopaixaorj**
+ Fix crash
+ isConnected()
+ hasListen()
+ resetReconnect()

@Credits: https://github.com/Leesneaks/otclientv8/commit/c72fdb5100510a03f5d5a52762c9adebdc4883f0

### CODE REVIEW

**Comment by ericcobblepot** [comment]
does mehah have  botserver?

@Nottinghster

**Comment by rodrigopaixaorj** [comment]
> does mehah have botserver?
> 
> @Nottinghster

Well, since it's the same from v8, every fix there, should be here too ;)

image

**Comment by ericcobblepot** [comment]
> > does mehah have botserver?
> > @Nottinghster
> 
> Well, since it's the same from v8, every fix there, should be here too ;)
> 


I understand about fixing bugs, but why **activate** something that doesn't work (currently) ?

**Comment by rodrigopaixaorj** [comment]
> > > does mehah have botserver?
> > > @Nottinghster
> > 
> > 
> > Well, since it's the same from v8, every fix there, should be here too ;)
> 
> I understand about fixing bugs, but why **activate** something that doesn't work (currently) ?

Because people can host their own bot servers and connect to those instead

**Comment by rodrigopaixaorj** [comment]
@ericcobblepot 

If you want to know why, here's the reason: https://discord.com/channels/965178465915633674/1216070153763295342

**Comment by ericcobblepot** [comment]
> Because people can host their own bot servers and connect to those instead

at least you testified it? @Nottinghster 

**OTClient Redemption:** 

image

ERROR: WebsocketSession error WebsocketSession unable to on_write ws://127.0.0.1:5000/send: The provided file handle is not valid.


### vs

**v8** 

image


if does not work, why do you activate it here? _Loader.lua

**Comment by rodrigopaixaorj** [comment]
> > Because people can host their own bot servers and connect to those instead
> 
> at least you testified it? @Nottinghster
> 
> **OTClient Redemption:**
> 
> image
> 
> ERROR: WebsocketSession error WebsocketSession unable to on_write ws://127.0.0.1:5000/send: The provided file handle is not valid.
> ### vs
> 
> **v8**
> 
> image
> 
> if does not work, why do you activate it here? _Loader.lua

I've deactivated again, it was a mistake...
But glad you've tested, personally, I don't use bot, but as I said before, the PR is created, if someone find bugs, create another PR fixing it, simple like that

**Pull request merged**
