### PR TITLE
Game prey draft

### PR DESCRIPTION
**Pull request by miah-sebastian**
# Description

Added game prey. It still needs prey task and pick specific monster. Also, there's a problem with the monsters showing, I don't think it's the code itself, I'm not sure what it is. When you relog, it shows most of them in the prey window, but if you reroll, for some reason most of them don't show again. The code is mostly from otcv8, which has MIT license, so I think it's ok.

## Type of change

Please delete options that are not relevant.

  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ x] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

**Test Configuration**:

  - Server Version: Canary 1.4.1
  - Client: 12.86
  - Operating System: Windows 10

## Checklist

  - [ x] My code follows the style guidelines of this project
  - [ x] I have performed a self-review of my own code
  - [ x] I checked the PR checks reports
  - [ x] I have commented my code, particularly in hard-to-understand areas
  - [ x] I have made corresponding changes to the documentation
  - [ x] My changes generate no new warnings
  - [ x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by mehah** [comment]
@miah-sebastian ,

could retest, the slot variable is missing.
image

and it has conflicts with main.
image

**Comment by miah-sebastian** [comment]
@mehah fixed and cleaned up, I'll wait until it's merged to fix game_imbuing, because it'll just make more conflicts. You might get a message about game_prey.otui spaces, almost every time I push a commit it messes with my line endings. I almost have game_shop ready, I'm polishing it, then I plan to do daily reward.

Also, I'm encountering a weird problem with UICreatures not loading, I imagine you'll know more about it. With the game_prey, if you log out and log back in, it'll display most of the creatures, but if you reroll, most of them don't appear. Same with game_shop, if I select the Outfits category, most won't load, but if I select a different category, then select Outfit category again, they all load this time.

**Comment by mehah** [comment]
I don't know about these problems, I'm not much for dealing with modules, at first you want to become a repository contributor, because I'm going to take a break from my activities and I need people who are willing to help.

**Comment by miah-sebastian** [comment]
@mehah game_imbuing is fixed. and okay, I'll look into it. and yeah, soon I won't have a whole lot of time either, I'm going back to school at the end of the month, but I'll still contribute when I can. I like the higher level stuff, creating from a base, the lower level stuff is stressful, makes my hair turn grey lol.

**Comment by mehah** [comment]
no problem, I just need a person who understands what's going on and solves it when he can, no need to get stuck in the project.

If you're interested, I'll send you an invite.

**Comment by miah-sebastian** [comment]
@mehah okay, sounds good, thank you.

**Comment by miah-sebastian** [comment]
@SkullzOTS thanks for cleaning that up. Have you noticed the problem with the monster outfits not loading? I've been trying to figure it out for like 2-3 days. If you log out and log back in, most load. I restructured it to send a Creature instead of an Outfit from protocolgameparse, and it seems to have made more load, but still not all, and still not the first time.

**Comment by SkullzOTS** [comment]
@miah-sebastian 
no...
I just noticed that I was printing errors in the terminal and decided to fix them, particularly I haven't tested this system yet!

**Pull request merged**
